import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link";

const Menu = () => {
  return (
    <div className="max-w-5xl mx-auto px-4 py-10">
      <h2 className="text-3xl font-bold mb-8 text-center">
        🍽️ Today’s Menu
      </h2>

      <div className="grid gap-6 sm:grid-cols-2 md:grid-cols-3">
        <Link
          href="/hamburger"
          className="group rounded-2xl border border-gray-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"
        >
          <h3 className="text-xl font-semibold group-hover:text-orange-600">
            Fredriks Burgare
          </h3>
          <p className="mt-2 text-sm text-gray-500">
            Juicy homemade burgers 🍔
          </p>
        </Link>

        <Link
          href="/biryani"
          className="group rounded-2xl border border-gray-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"
        >
          <h3 className="text-xl font-semibold group-hover:text-orange-600">
            Elviras Biryani
          </h3>
          <p className="mt-2 text-sm text-gray-500">
            Spicy & aromatic rice 🍚
          </p>
        </Link>

        <Link
          href="/korvstroganof"
          className="group rounded-2xl border border-gray-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"
        >
          <h3 className="text-xl font-semibold group-hover:text-orange-600">
            Klings Korvstroganof
          </h3>
          <p className="mt-2 text-sm text-gray-500">
            Classic Swedish comfort food 🇸🇪
          </p>
        </Link>
      </div>
    </div>
  );
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><Menu/>
        {children}
      </body>
    </html>
  );
}
